// electron/vite-vue-better-sqlite/src/renderer/src/components/Navbar.vue
<template lang="">
  <div>
    <router-link to="/" class="links" exact-active-class="active">Home</router-link>
    <router-link to="/login" class="links" exact-active-class="active">Login</router-link>
    <router-link to="/register" class="links" exact-active-class="active">Register</router-link>
  </div> 
</template>

// electron/vite-react/src/renderer/src/components/Navbar.jsx
import { NavLink } from 'react-router-dom'

export default function navbar() {
  return (
    <>
      <nav className="navbar">
        <NavLink to="/" className="links">
          Home
        </NavLink>
        <NavLink to="/login" className="links">
          Login
        </NavLink>
        <NavLink to="/register" className="links">
          Register
        </NavLink>
      </nav>
    </>
  )
}
